/*
  ==============================================================================

	This file was auto-generated by the Introjucer!

	It contains the basic startup code for a Juce application.

  ==============================================================================
*/


#include "../JuceLibraryCode/JuceHeader.h"
#include "pfm2Window.h"



//==============================================================================
class pfm2EditorApplication : public JUCEApplication
{
public:
	//==============================================================================
	pfm2EditorApplication() {
	}

	const String getApplicationName() override { return ProjectInfo::projectName; }
	const String getApplicationVersion() override { return ProjectInfo::versionString; }
	bool moreThanOneInstanceAllowed() override { return true; }

	//==============================================================================
	void initialise(const String& commandLine) override
	{
		// Add your application's initialisation code here...

		mainWindow = new StandalonePFM2Window("Ixox Shruthi Editor", Colour(0xff183B46), nullptr);
		mainWindow->setVisible(true);
		mainWindow->setResizable(true, true);
	}

	void shutdown() override
	{
		// Add your application's shutdown code here..
		delete mainWindow;
	}

	//==============================================================================
	void systemRequestedQuit() override
	{
		// This is called when the app is being asked to quit: you can ignore this
		// request and let the app carry on running, or call quit() to allow the app to close.
		quit();
	}

	void anotherInstanceStarted(const String& commandLine) override
	{
		// When another instance of the app is launched while this one is running,
		// this method is invoked, and the commandLine parameter tells you what
		// the other instance's command-line arguments were.
	}

	StandalonePFM2Window* mainWindow;
};

//==============================================================================
// This macro generates the main() routine that launches the app.
START_JUCE_APPLICATION(pfm2EditorApplication)


